ARG SOURCE_IMAGE_NAME="${SOURCE_IMAGE_NAME:-wolfi-toolbox}"
ARG SOURCE_IMAGE_REGISTRY="${SOURCE_IMAGE_REGISTRY:-ghcr.io/ublue-os}"
ARG SOURCE_IMAGE="${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}"

FROM $SOURCE_IMAGE:latest

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the Toolbox or Distrobox commands" \
      summary="A terminal experience powered by Wolfi and Homebrew, adapted from ublue-os/toolboxes" \
      maintainer="michael.haaf@gmail.com"

COPY ./boxkits/cli/packages.cli /toolbox-packages
COPY ./boxkits/cli/files /

# Update image, Install Packages, and move /home/linuxbrew
RUN apk update && \
    apk upgrade && \
    grep -v '^#' /toolbox-packages | xargs apk add && \
    mv /home/linuxbrew /home/homebrew && \
    rm /toolbox-packages

# Patch /usr/bin/entrypoint
RUN sed -i '/missing_packages=0/,/# Set SHELL to the install path inside the container/ s/^/#/' /usr/bin/entrypoint && \
    sed -i '/# Set SHELL to the install path inside the container/a touch /.containersetupdone' /usr/bin/entrypoint

# Use and configure bash, retrieve bash-prexec
RUN curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o /tmp/bash-prexec && \
    mkdir -p /usr/share/ && \
    cp /tmp/bash-prexec /usr/share/bash-prexec && \
    rm -rf /tmp/*

# TODO: modularize like the above bash-preexecs
# Link other host utilities
RUN \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/pass && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/pass-otp && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/wl-copy && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/wl-paste && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/wtype && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/fuzzel && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/journalctl
